export enum PermissionOverrideType {
  GRANT = "GRANT",
  DENY = "DENY",
}

export enum Role {
  USER = "USER",
  HOST = "HOST",
  MODERATOR = "MODERATOR",
  OWNER_ADMIN = "OWNER_ADMIN",
}

export enum AccountStatus {
  ACTIVE = "ACTIVE",
  PENDING_EMAIL_VERIFICATION = "PENDING_EMAIL_VERIFICATION",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  DEACTIVATED = "DEACTIVATED",
  DELETION_PENDING = "DELETION_PENDING",
}

export enum HostApplicationStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED",
  PAYMENT_VERIFICATION_REQUIRED = "PAYMENT_VERIFICATION_REQUIRED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
  REVOKED = "REVOKED",
  WITHDRAWN = "WITHDRAWN",
}

export enum StreamingPlatform {
  KICK = "KICK",
  YOUTUBE = "YOUTUBE",
  TIKTOK = "TIKTOK",
  FACEBOOK = "FACEBOOK",
  TWITCH = "TWITCH",
}

export enum PayoutProvider {
  STRIPE = "STRIPE",
}

export enum LiveSessionStatus {
  SCHEDULED = "SCHEDULED",
  PREPARING = "PREPARING",
  LIVE = "LIVE",
  PAUSED = "PAUSED",
  ENDING = "ENDING",
  ENDED = "ENDED",
  CANCELLED = "CANCELLED",
}

export enum ReservationStatus {
  ACTIVE = "ACTIVE",
  CONSUMED = "CONSUMED",
  EXPIRED = "EXPIRED",
  RELEASED = "RELEASED",
  CANCELLED = "CANCELLED",
}

export enum QueueStatus {
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  QUEUED = "QUEUED",
  NEXT = "NEXT",
  PLAYING = "PLAYING",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
  REJECTED = "REJECTED",
  REMOVED = "REMOVED",
  CARRIED_OVER = "CARRIED_OVER",
  REFUND_PENDING = "REFUND_PENDING",
  REFUNDED = "REFUNDED",
  EXPIRED = "EXPIRED",
  MOVED_TO_HISTORY = "MOVED_TO_HISTORY",
}

export enum QueueBatchOperationType {
  MOVE_TO_HISTORY = "MOVE_TO_HISTORY",
  REINSERT_TO_QUEUE = "REINSERT_TO_QUEUE",
  REMOVE_FROM_ACTIVE_QUEUE = "REMOVE_FROM_ACTIVE_QUEUE",
}

export enum TierColorSlot {
  FREE_LINE = "FREE_LINE",
  TIER_COLOR_1 = "TIER_COLOR_1",
  TIER_COLOR_2 = "TIER_COLOR_2",
  TIER_COLOR_3 = "TIER_COLOR_3",
  TIER_COLOR_4 = "TIER_COLOR_4",
  TIER_COLOR_5 = "TIER_COLOR_5",
  TIER_COLOR_6 = "TIER_COLOR_6",
  TIER_COLOR_7 = "TIER_COLOR_7",
  TIER_COLOR_8 = "TIER_COLOR_8",
  TIER_COLOR_9 = "TIER_COLOR_9",
  TIER_COLOR_10 = "TIER_COLOR_10",
}

export enum PaymentStatus {
  CREATED = "CREATED",
  REQUIRES_ACTION = "REQUIRES_ACTION",
  AUTHORIZED = "AUTHORIZED",
  CAPTURED = "CAPTURED",
  SETTLED = "SETTLED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  REFUNDED = "REFUNDED",
  DISPUTED = "DISPUTED",
  CHARGEBACK = "CHARGEBACK",
}

export enum HostEarningStatus {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  ALLOCATED_TO_STRIPE = "ALLOCATED_TO_STRIPE",
  REVERSED = "REVERSED",
  REFUNDED = "REFUNDED",
  DISPUTED = "DISPUTED",
}

export enum PayoutStatus {
  PENDING = "PENDING",
  IN_TRANSIT = "IN_TRANSIT",
  PAID = "PAID",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum ReportStatus {
  OPEN = "OPEN",
  UNDER_REVIEW = "UNDER_REVIEW",
  ACTIONED = "ACTIONED",
  DISMISSED = "DISMISSED",
  APPEALED = "APPEALED",
  CLOSED = "CLOSED",
}

export enum BanScope {
  ACCOUNT = "ACCOUNT",
  HOST_PRIVILEGES = "HOST_PRIVILEGES",
  SUBMISSIONS = "SUBMISSIONS",
  PAYMENTS = "PAYMENTS",
  PAYOUTS = "PAYOUTS",
  CONTENT_UPLOAD = "CONTENT_UPLOAD",
  IP = "IP",
  NETWORK = "NETWORK",
  DEVICE_RISK = "DEVICE_RISK",
  FULL_PLATFORM = "FULL_PLATFORM",
}

export enum TrackSourceType {
  UPLOADED_AUDIO = "UPLOADED_AUDIO",
  YOUTUBE = "YOUTUBE",
  SOUNDCLOUD = "SOUNDCLOUD",
  SPOTIFY = "SPOTIFY",
  BANDCAMP = "BANDCAMP",
  DIRECT_AUDIO_URL = "DIRECT_AUDIO_URL",
  OTHER_EXTERNAL = "OTHER_EXTERNAL",
}

export enum PlaybackCapability {
  NATIVE_AUDIO = "NATIVE_AUDIO",
  EMBEDDED_PLAYER = "EMBEDDED_PLAYER",
  EXTERNAL_ONLY = "EXTERNAL_ONLY",
  UNSUPPORTED = "UNSUPPORTED",
}

export enum ProcessingState {
  UPLOADING = "UPLOADING",
  PROCESSING = "PROCESSING",
  READY = "READY",
  FAILED = "FAILED",
}

export enum UploadIntentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum UploadIntentType {
  TRACK_AUDIO = "TRACK_AUDIO",
  TRACK_ARTWORK = "TRACK_ARTWORK",
}

export enum InvitationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REVOKED = "REVOKED",
  EXPIRED = "EXPIRED",
}

export enum StripePlatformMode {
  TEST = "TEST",
  LIVE = "LIVE",
}

export enum PaymentEmergencyState {
  PAYMENTS_ENABLED = "PAYMENTS_ENABLED",
  PAYMENTS_PAUSED = "PAYMENTS_PAUSED",
  PAYMENTS_DISABLED = "PAYMENTS_DISABLED",
}

export enum StationStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ARCHIVED = "ARCHIVED",
}

export enum AdminPermission {
  ADMIN_PLATFORM_FULL = "ADMIN_PLATFORM_FULL",
  ADMIN_MODERATOR_MANAGE = "ADMIN_MODERATOR_MANAGE",
  ADMIN_ROLE_MANAGE = "ADMIN_ROLE_MANAGE",
  STRIPE_PLATFORM_CONFIGURE = "STRIPE_PLATFORM_CONFIGURE",
  STRIPE_PLATFORM_VIEW_STATUS = "STRIPE_PLATFORM_VIEW_STATUS",
  PAYMENT_CONFIGURATION_MANAGE = "PAYMENT_CONFIGURATION_MANAGE",
  PLATFORM_COMMISSION_MANAGE = "PLATFORM_COMMISSION_MANAGE",
  HOST_APPLICATION_MANAGE = "HOST_APPLICATION_MANAGE",
  USER_BAN_MANAGE = "USER_BAN_MANAGE",
  CONTENT_MODERATE = "CONTENT_MODERATE",
  PAYMENT_RECORD_VIEW = "PAYMENT_RECORD_VIEW",
  REFUND_MANAGE = "REFUND_MANAGE",
  DISPUTE_REVIEW = "DISPUTE_REVIEW",
  AUDIT_LOG_VIEW = "AUDIT_LOG_VIEW",
  PLATFORM_SETTINGS_MANAGE = "PLATFORM_SETTINGS_MANAGE",
}

// ============================================================================
// Worker Job Contracts
// ============================================================================

export enum MediaJobName {
  EXTRACT_AUDIO_METADATA = "EXTRACT_AUDIO_METADATA",
  PROCESS_ARTWORK = "PROCESS_ARTWORK",
  GENERATE_WAVEFORM = "GENERATE_WAVEFORM",
  TRANSCODE_AUDIO = "TRANSCODE_AUDIO",
  ANALYZE_LOUDNESS = "ANALYZE_LOUDNESS",
  DETECT_SILENCE = "DETECT_SILENCE",
  MALWARE_SCAN = "MALWARE_SCAN",
}

export interface ExtractAudioMetadataPayload {
  trackId: string;
  mediaVersionId: string;
  ownerUserId: string;
  objectKey: string;
  correlationId?: string;
}

export interface ProcessArtworkPayload {
  trackId: string;
  artworkId: string;
  ownerUserId: string;
  objectKey: string;
  correlationId?: string;
}

export interface User {
  id: string;
  email: string;
  username: string;
  displayName: string;
  accountStatus: AccountStatus;
  emailVerified: boolean;
  createdAt: Date;
  updatedAt: Date;
}
